BBBB BBBB BBBBBBXXXXXXXXX XXXXX
BBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBB
XXXXX XXXXXXFFFFFFFFFFFFFFFX XXXXXFFFFFFFFFFFFFFFFFFFFXX
XXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX
XXXXXX
    XXXXXXXBBBBB BBBBBBBBBBBBBXXXXXXXX
XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXBBBBB BBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBXX
BB BBB BBBBBBBB BBB BBBBBBBBBBBBBBBBBBBBBB
  XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBXX
  XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXX
BBBBB
BBBBB BBBBBBBBBBBBBBBBBB
BB BBBBBBBBBBBBBXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXBBBBB BBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBXXBBBBB
BBBBB BBBBBBBBBBBBBBBBB
BBBBB BBBBBBBBBB
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBXX
    BB BBBBBBBBBBBBBXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXBBBBB
BBBBBBBB
BBBBB BBBBBBBBBXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXBBBBBBBB
XXXXXXX
BBBB BBBB

XXXXX XXXXXXXBB BBBBBBBBXXXXX BBBBBBBBBB BBBBBBBBBBBBBBBBBX
  XXXXXXXXXXXXXXXXXXXXXXXBBB BBBXX

XXXX XXXXXXXXX XXX
XXXX XXXXXXXXXXXXXXX

    BB BBB BBBBBBBB
    XXXX XXXXXX XXX
    XXXX XXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXX
        BBBBB BBBBBBBBBBBBBBBB
        XXXXXX
        BBBBB BBBBBBBBB
        BB BBBBBBBBBBBBBB
        XXXX XXXXXXXXXXXXXXXX
            BBBBB BBBBBBBBBBB
XXXX                 gettext(u'Welcome,') XXX
XXXX                XXXXXXXXBBBBBBB BBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBXXXXXXXXXXXXX
XXXX            BBBBBBBBXXX
XXXX            BBBBB BBBBBBBBBXXX
XXXX                BB BBBBBBBBXXX
XXXX                    XX XXXXXXXX gettext(u'View site') XXXX XXXX
XXXX                BBBBBXXX
XXXX                BB BBBBBBBBBBBBBB BBB BBBBBBBBBBBBBXXX
XXXX                    BBB BBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBXXX
XXXX                    BB BBBBBBBBXXX
XXXX                        XX XXXXXXXX gettext(u'Documentation') XXXX XXXX
XXXX                    BBBBBXXX
XXXX                BBBBBXXX
XXXX                BB BBBBBBBBBBBBBBBBBBBBBBBBXXX
XXXX                XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBXX gettext(u'Change password') XXXX XXXX
XXXX                BBBBBXXX
                XX XXXXXXBBB BBBBBBBBBBBBBBXX gettext(u'Log out') XXXX
            BBBBBBBB
        XXXXXX
        BBBBB
        BBBBBBBB
        BBBBB BBBBBBBBBBBBBBBBBB
    XXXXXX
    XXXX XXX XXXXXX XXX
    BBBBB BBBBBBBBBBB
    XXXX XXXXXXXXXXXXXXXXXXXX
    XX XXXXXXBBB BBBBBBBBBBBBBXX gettext(u'Home') XXXX
    BB BBBBB XXXXXXXX BBBBB
    XXXXXX
    BBBBBBBB
    BBBBB

    XXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXX
XXXX      BB BBB BBBBBBBB BBB BBBBBBBBBBBBBBBBBBBBBBXXX
XXXX        BBBBB BBBBBBBBBBBXXX
XXXX          BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBXXX
XXXX        BBBBBBBBXXX
XXXX      BBBBBXXX
      XXXX XXXXXXXXXXXXXXXX
        BBBBB BBBBBBBB
          BB BBBBBBBB
            XXX XXXXXXXXXXXXXXXXXXXXBBB BBBBBBB BB BBBBBBBB
              XXXBB BBBBBBBBBBBB XXXXXXXXBBBBBXFFFFFFFFXXXXX
            BBBBBBXXXXX
          BBBBB
        BBBBBBBB BBBBBBBB
        XXXX XXXXXXX XXX
        XXXX XXXXXXXXXXXX XXXXXXXBBBBB BBBBBBBXXXXBBBBBBBBXX
          BBBBB BBBBBBBBBBBBBBBB
            XXXX
            XXXX
            XXXX
XXXX          BBBBB BBBBBBBBBBBBBBB BBBBBXXXXXXXXXBBBBBBBBBBBBBXXX
            BBBBB BBBBBBBBBBBBBBBBBB BBBBBBBBXXXXXXXXXBBBBBBBBBBBBB
          BBBBB BBBBBBB
            BBBBB BBBBBBBBBBBBBBBBBBBB
            
          BBBBBBBB
XXXX          BBBBB BBBBBBBBBBBBBBBXXX
          XXX XXXXXXXXXXXXXX
        XXXXXX
        XXXX XXX XXXXXXX XXX
        BBBBB BBBBBBXXXX XXXXXXXXXXXXXXXXXXBBBBBBBB
      XXXXXX
    XXXXXX
XXXXXX
XXXX XXX XXXXXXXXX XXX
XXXXXXX
XXXXXXX
