# Generated by Django 3.2.6 on 2021-09-25 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_company_name',
            field=models.CharField(max_length=200, verbose_name='customer company name'),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='نام محصول')),
                ('description', models.TextField()),
                ('contact_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='support.customer')),
            ],
            options={
                'verbose_name': ' سرویس ها ',
                'verbose_name_plural': ' سرویس ها ',
            },
        ),
        migrations.CreateModel(
            name='ProductOwnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_serial_number', models.IntegerField()),
                ('customer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='support.customer')),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='support.product')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_product',
            field=models.ManyToManyField(through='support.ProductOwnership', to='support.Product'),
        ),
    ]
