# Generated by Django 3.2.6 on 2021-10-07 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partpack',
            name='part_quantity',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='partpack',
            name='part_repair_cost',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_model',
            field=models.CharField(choices=[('BASIC', 'BASIC'), ('ECO', 'ECONOMY'), ('PRO', 'PROFESSIONAL'), ('FULL', 'FULL')], default='eco', max_length=200, verbose_name='Product model'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_part',
            field=models.ManyToManyField(blank=True, through='support.PartPack', to='support.Part'),
        ),
    ]
