# Generated by Django 3.2.6 on 2021-09-25 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_auto_20210926_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='product_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='support.productownership'),
        ),
    ]
