# Generated by Django 3.2.6 on 2021-10-09 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_auto_20211008_2358'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(blank=True, max_length=100, verbose_name='Part Supplier Name')),
                ('supplier_phone', models.CharField(blank=True, max_length=20, verbose_name='Part Supplier Phone')),
                ('supplier_address', models.CharField(blank=True, max_length=400, verbose_name='Part Supplier Address')),
                ('supplier_description', models.TextField(blank=True, max_length=1000, verbose_name='Part Description')),
            ],
            options={
                'verbose_name': 'Part',
                'verbose_name_plural': 'Parts',
            },
        ),
    ]
