# Generated by Django 3.2.6 on 2021-09-26 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0004_auto_20210926_0159'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='part_description',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Part Description'),
        ),
        migrations.AddField(
            model_name='part',
            name='part_supplier_address',
            field=models.CharField(blank=True, max_length=400, verbose_name='Part Supplier Address'),
        ),
        migrations.AddField(
            model_name='part',
            name='part_supplier_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Part Supplier Name'),
        ),
        migrations.AddField(
            model_name='part',
            name='part_supplier_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Part Supplier Phone'),
        ),
        migrations.AlterField(
            model_name='part',
            name='part_name',
            field=models.CharField(max_length=100, verbose_name='Part Name'),
        ),
    ]
