# Generated by Django 3.2.6 on 2021-10-09 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0004_supplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='part_supplier_address',
        ),
        migrations.RemoveField(
            model_name='part',
            name='part_supplier_name',
        ),
        migrations.RemoveField(
            model_name='part',
            name='part_supplier_phone',
        ),
        migrations.AddField(
            model_name='part',
            name='part_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='support.supplier'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplier_name',
            field=models.CharField(max_length=100, verbose_name='Part Supplier Name'),
        ),
    ]
